export const Colors = {
  // UI tokens
  background: 'var(--background)',
  foreground: 'var(--foreground)',
  card: 'var(--card)',
  'card-foreground': 'var(--card-foreground)',
  popover: 'var(--popover)',
  'popover-foreground': 'var(--popover-foreground)',
  primary: 'var(--primary)',
  'primary-foreground': 'var(--primary-foreground)',
  secondary: 'var(--secondary)',
  'secondary-foreground': 'var(--secondary-foreground)',
  muted: 'var(--muted)',
  'muted-foreground': 'var(--muted-foreground)',
  accent: 'var(--accent)',
  'accent-foreground': 'var(--accent-foreground)',
  destructive: 'var(--destructive)',
  'destructive-foreground': 'var(--destructive-foreground)',
  border: 'var(--border)',
  input: 'var(--input)',
  ring: 'var(--ring)',

  // Pokémon type tokens
  'type-normal': 'var(--type-normal)',
  'type-normal-foreground': 'var(--type-normal-foreground)',
  'type-fire': 'var(--type-fire)',
  'type-fire-foreground': 'var(--type-fire-foreground)',
  'type-water': 'var(--type-water)',
  'type-water-foreground': 'var(--type-water-foreground)',
  'type-electric': 'var(--type-electric)',
  'type-electric-foreground': 'var(--type-electric-foreground)',
  'type-grass': 'var(--type-grass)',
  'type-grass-foreground': 'var(--type-grass-foreground)',
  'type-ice': 'var(--type-ice)',
  'type-ice-foreground': 'var(--type-ice-foreground)',
  'type-fighting': 'var(--type-fighting)',
  'type-fighting-foreground': 'var(--type-fighting-foreground)',
  'type-poison': 'var(--type-poison)',
  'type-poison-foreground': 'var(--type-poison-foreground)',
  'type-ground': 'var(--type-ground)',
  'type-ground-foreground': 'var(--type-ground-foreground)',
  'type-flying': 'var(--type-flying)',
  'type-flying-foreground': 'var(--type-flying-foreground)',
  'type-psychic': 'var(--type-psychic)',
  'type-psychic-foreground': 'var(--type-psychic-foreground)',
  'type-bug': 'var(--type-bug)',
  'type-bug-foreground': 'var(--type-bug-foreground)',
  'type-rock': 'var(--type-rock)',
  'type-rock-foreground': 'var(--type-rock-foreground)',
  'type-ghost': 'var(--type-ghost)',
  'type-ghost-foreground': 'var(--type-ghost-foreground)',
  'type-dragon': 'var(--type-dragon)',
  'type-dragon-foreground': 'var(--type-dragon-foreground)',
  'type-dark': 'var(--type-dark)',
  'type-dark-foreground': 'var(--type-dark-foreground)',
  'type-steel': 'var(--type-steel)',
  'type-steel-foreground': 'var(--type-steel-foreground)',
  'type-fairy': 'var(--type-fairy)',
  'type-fairy-foreground': 'var(--type-fairy-foreground)',
  'type-stellar': 'var(--type-stellar)',
  'type-stellar-foreground': 'var(--type-stellar-foreground)',
  'type-unknown': 'var(--type-unknown)',
  'type-unknown-foreground': 'var(--type-unknown-foreground)',

  // Stat tokens
  'stat-hp': 'var(--stat-hp)',
  'stat-attack': 'var(--stat-attack)',
  'stat-defense': 'var(--stat-defense)',
  'stat-special-attack': 'var(--stat-special-attack)',
  'stat-special-defense': 'var(--stat-special-defense)',
  'stat-speed': 'var(--stat-speed)',
} as const;

export type Color = keyof typeof Colors;

export type ColorValue = (typeof Colors)[Color];
